### ISSUE TITLE
「full_address」メソッドの使用例コメントが実際の結果と異なっている

### ISSUE THREAD

**Issue by takatea** [yamat47/japanese_address_parser#100]
Actual実行結果が正しいと思うので、READMEを修正するPRを作成いたします！

### Expected

```ruby
address = JapaneseAddressParser.call('東京都港区芝公園4-2-8')
address.full_address #=> "東京都港区芝公園4-2-8"
```

### Actual

```ruby
address = JapaneseAddressParser.call('東京都港区芝公園4-2-8')
address.full_address #=> "東京都港区芝公園四丁目"
```

**Comment by yamat47** [comment]
@takatea issue の作成ありがとうございます！

こちらですが、API の仕様として Expeced を意図したものでして...
それが意図せず変わってしまっていた、というのが現状の課題ですね...

README のような処理に戻したいと思うので、対応します！
（プルリクエストを作ってくださったと思うのですが、閉じてしまうかもしれません）

**Comment by takatea** [comment]
@yamat47 

ありがとうございます！

>こちらですが、API の仕様として Expeced を意図したものでして...
それが意図せず変わってしまっていた、というのが現状の課題ですね...

callに渡されたものをfull_addressというインスタンス変数に入れていたのですね！
実装あまり見ずにIssue作ってしまいました...！🙇‍♂️

正規化された後の結果がfull_addressだとおもっておりました。
特に、furiganaというメソッドもあるので、それと対応しているものだとおもっておりました。
利用する側としては、callされた後に呼び出せるものなので正規化後であるのが自然に感じてしまっていたのかもしれません。

---

その上で、個人的に正規化後の住所を確認するメソッドがあってもいいかもと思いましたがどうでしょうか？

`normalized_address` 、`formatted_address`みたいなメソッドがあると良いかもしれません！
そうすれば利用側で正規化された後のデータをjoinする手間が省けて少し嬉しいです！
以下がイメージです！

```
address.full_address #=> "東京都港区芝公園4-2-8"
address.normalized_address #=> "東京都港区芝公園四丁目"
address.furigana #=> "トウキョウトミナトクシバコウエン 4"
```

私の方でお手伝いすることも可能です！！ご検討いただけると幸いです！

**Comment by yamat47** [comment]
@takatea https://github.com/yamat47/japanese_address_parser/pull/102 にて、README に載っている挙動に揃える変更をしました。
こちらと、関連するプルリクエスト（ #101 ）は閉じてしまいます、ありがとうございました！
