### ISSUE TITLE
「愛知県名古屋市中村区名駅1-1-10」のふりがなデータが正しくない。

### ISSUE THREAD

**Issue by champierre** [yamat47/japanese_address_parser#31]
```
pry(main)> JapaneseAddressParser.call('愛知県名古屋市中村区名駅1-1-10').furigana => "アイチケンナゴヤシナカムラクメイエキ(1-1-8、1-1-12、1-1-13、1-1-14、1-3-4、 1"
```

「愛知県名古屋市中村区名駅1-1-10」のふりがなデータが正しくない。
「アイチケンナゴヤシナカムラクメイエキ 1」と返してほしい。

**Comment by champierre** [comment]
japanese-addresses の元データがおかしい。
https://github.com/geolonia/japanese-addresses/issues/89

**Comment by yamat47** [comment]
https://japanese-address-parser-demo.herokuapp.com/?search=%E6%84%9B%E7%9F%A5%E7%9C%8C%E5%90%8D%E5%8F%A4%E5%B1%8B%E5%B8%82%E4%B8%AD%E6%9D%91%E5%8C%BA%E5%90%8D%E9%A7%851-1-10

メモ：デモのサイトでも同様の結果になります。

**Comment by champierre** [comment]
@yamat47 https://github.com/geolonia/japanese-addresses/pull/111 で修正しました。最新の latest.csv をデータ元にすれば直ると思います。

**Comment by yamat47** [comment]
### 参照するデータを更新する手順
1. ライブラリのアップデート
2. `bin/console` でコンソールを起動。
   
   ```ruby
   require_relative 'lib/japanese_address_parser/csv_parser'
   JapaneseAddressParser::CsvParser.call
   ```

**Comment by yamat47** [comment]
```ruby
irb(main):003:0> JapaneseAddressParser.call('愛知県名古屋市中村区名駅1-1-10').furigana
=> "アイチケンナゴヤシナカムラクメイエキ 1"
```

素晴らしい！

**Comment by yamat47** [comment]
@champierre ライブラリの更新ありがとうございました！
こちらにも取り込めて、無事動作が改善しました 🚀

**Comment by champierre** [comment]
@yamat47 [デモサイト](https://japanese-address-parser-demo.herokuapp.com/)で確認しました。どうもありがとうございます。
